/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CloudIdentityGroupObservation struct {
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`
}

type CloudIdentityGroupParameters struct {

	// An extended description to help users determine the purpose of a Group.
	// Must not be longer than 4,096 characters.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The display name of the Group.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// EntityKey of the Group.
	// +kubebuilder:validation:Required
	GroupKey []GroupKeyParameters `json:"groupKey" tf:"group_key,omitempty"`

	// The initial configuration options for creating a Group.
	//
	// See the
	// [API reference](https://cloud.google.com/identity/docs/reference/rest/v1beta1/groups/create#initialgroupconfig)
	// for possible values. Default value: "EMPTY" Possible values: ["INITIAL_GROUP_CONFIG_UNSPECIFIED", "WITH_INITIAL_OWNER", "EMPTY"]
	// +kubebuilder:validation:Optional
	InitialGroupConfig *string `json:"initialGroupConfig,omitempty" tf:"initial_group_config,omitempty"`

	// The labels that apply to the Group.
	//
	// Must not contain more than one entry. Must contain the entry
	// 'cloudidentity.googleapis.com/groups.discussion_forum': '' if the Group is a Google Group or
	// 'system/groups/external': '' if the Group is an external-identity-mapped group.
	// +kubebuilder:validation:Required
	Labels map[string]*string `json:"labels" tf:"labels,omitempty"`

	// The resource name of the entity under which this Group resides in the
	// Cloud Identity resource hierarchy.
	//
	// Must be of the form identitysources/{identity_source_id} for external-identity-mapped
	// groups or customers/{customer_id} for Google Groups.
	// +kubebuilder:validation:Required
	Parent *string `json:"parent" tf:"parent,omitempty"`
}

type GroupKeyObservation struct {
}

type GroupKeyParameters struct {

	// The ID of the entity.
	//
	// For Google-managed entities, the id must be the email address of an existing
	// group or user.
	//
	// For external-identity-mapped entities, the id must be a string conforming
	// to the Identity Source's requirements.
	//
	// Must be unique within a namespace.
	// +kubebuilder:validation:Required
	ID *string `json:"id" tf:"id,omitempty"`

	// The namespace in which the entity exists.
	//
	// If not specified, the EntityKey represents a Google-managed entity
	// such as a Google user or a Google Group.
	//
	// If specified, the EntityKey represents an external-identity-mapped group.
	// The namespace must correspond to an identity source created in Admin Console
	// and must be in the form of 'identitysources/{identity_source_id}'.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

// CloudIdentityGroupSpec defines the desired state of CloudIdentityGroup
type CloudIdentityGroupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CloudIdentityGroupParameters `json:"forProvider"`
}

// CloudIdentityGroupStatus defines the observed state of CloudIdentityGroup.
type CloudIdentityGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CloudIdentityGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// CloudIdentityGroup is the Schema for the CloudIdentityGroups API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,tfgcp}
type CloudIdentityGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CloudIdentityGroupSpec   `json:"spec"`
	Status            CloudIdentityGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CloudIdentityGroupList contains a list of CloudIdentityGroups
type CloudIdentityGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CloudIdentityGroup `json:"items"`
}

// Repository type metadata.
var (
	CloudIdentityGroupKind             = "CloudIdentityGroup"
	CloudIdentityGroupGroupKind        = schema.GroupKind{Group: Group, Kind: CloudIdentityGroupKind}.String()
	CloudIdentityGroupKindAPIVersion   = CloudIdentityGroupKind + "." + GroupVersion.String()
	CloudIdentityGroupGroupVersionKind = GroupVersion.WithKind(CloudIdentityGroupKind)
)

func init() {
	SchemeBuilder.Register(&CloudIdentityGroup{}, &CloudIdentityGroupList{})
}
