apiVersion: storage.gcp.jet.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: example
  annotations:
    # Note that this will be the actual bucket name, so it has to be globally
    # unique/available.
    crossplane.io/external-name: crossplane-example-bucket-test-332
spec:
  forProvider:
    location: US
    storageClass: MULTI_REGIONAL
